name: oscam-emu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static:register --reset $$ \ docker build   --no-cache   --pull   -t oscam:latest  -f Dockerfile
